name: Daily Commit

on:
  schedule:
    - cron: '35 13 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:     # Allows manual run

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a dummy change
      run: |
        date >> daily.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "PratikChaudhari15"
        git config --global user.email "pratik.chaudhari15.03@gmail.com"
        git add .
        git commit -m "Daily commit $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
