name: 🔄 Daily Auto Commit

on:
  schedule:
    - cron: '15 13 * * *' # 6:45 PM IST
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: 🧹 Clear and Update .txt Files
        run: |
          find . -name "*.txt" -type f -exec sh -c '> "$1"' _ {} \;
          echo "Updated on $(date -u)" >> daily-log.txt

      - name: ✅ Commit and Push Changes
        run: |
          git config user.name "PratikChaudhari15"
          git config user.email "pratik.chaudhari15.03@gmail.com"

          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "📅 Auto commit: $(date -u)"
            git push
          fi
